name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-sbt-libs
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier
        key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
